### ISSUE TITLE
After reboot, previously loaded playlist cannot be started

### ISSUE THREAD

**Issue by Darmur** [volumio/new-spotify-plugin#12]
1) loaded playlist
2) playback of a few tracks working fine
3) stop playback
4) reboot
5) tried playback of the playlist, doesn't work
6) sent system log

after the reboot, the previously loaded playlist cannot be started, here the system log
http://logs.volumio.org/motivo/PP8Z4mf.html

disablig/enabling the plugin didn't work

logging out and then logging in again, made the playback working, without touching the playlist
http://logs.volumio.org/motivo/YJdBUqJ.html

@volumio @devgianlu

**Comment by volumio** [comment]
please let's not tag gianlu here.
reported the problem, its related to login

**Comment by Darmur** [comment]
OK!
